const CartActionTypes = {
    TOGGLE_CART_HIDDEN:'TOGGLE_CART_HIDDEN',
    ADD_ITEM:'ADD_ITEM',
    CLEAR_CART_ITEM:'CLEAR_CART_ITEM',
    REMOVE_CART_ITEM:'REMOVE_CART_ITEM'
};


export default CartActionTypes;